//This file interfaces a RGB Led and color sensor to Atmega2560 Microcontroller
/*
 * Color_Sensor.c
 *
 * Created: 01-12-2018 14:45:11
 *  Author: e-Yantra Team
 
This experiment demonstrates the use of Color Sensor.

Micro-controller: atmega2560
Optimization: -O0  (For more information read section: Selecting proper optimization
options below figure 2.22 in the Software Manual)
*/

#define F_CPU 16000000
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <math.h> //included to support power function

//You can declare here global variable as per your requirement

void rgb_port_config (void)
{
	/*****************************************
	Define DDR and PORT values for the port on which RGB LED is connected
	******************************************/
	//for RGB port B
	DDRB = 0b11100000;
}

void color_sensor_pin_config(void)
{
	/*****************************************
	Define DDR and PORT values for the port on which Color sensor is connected
	******************************************/
	DDRC = 0b10101010; //for pins S0 S1 S2 and S3
	DDRD = 0b00000000; //for pins OUT
}


void color_sensor_pin_interrupt_init(void) //Interrupt 0 enable
{
	cli(); //Clears the global interrupt
	EICRA |= (1<<0b1);  // INT0 is set to trigger with falling edge
	EIMSK |= (1<<INT0);  // Enable Interrupt INT0 for color sensor
	sei(); // Enables the global interrupt
}

//ISR for color sensor
ISR(INT0_vect)
{
	//increment on receiving pulse from the color sensor
}

void init_devices(void)
{
	cli(); //Clears the global interrupt
	//Initialize all the ports here
	rgb_port_config ();
	color_sensor_pin_config();
	color_sensor_pin_interrupt_init();
	sei();   // Enables the global interrupt
}

//Filter Selection
void filter_red(void)    //Used to select red filter
{
	//Filter Select - red filter
	 //S2 and S3 should be low
	 PORTC = 0b00001010;
}

void filter_green(void)	//Used to select green filter
{
	//Filter Select - green filter
	//S2 and S3 should be high
	PORTC = 0b10100000;
}

void filter_blue(void)	//Used to select blue filter
{
	//Filter Select - blue filter
	//S2 low and S3 High
	PORTC = 0b10000000;
}

void filter_clear(void)	//select no filter
{
	//Filter Select - no filter
	//S2 high and S3 low
	PORTC = 0b00100000;
}

//Color Sensing Scaling
void color_sensor_scaling()		//This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 20% scaling is preferable, though you can change the values as per your application by referring datasheet
{
	//Output Scaling 20% from datasheet
	
	//set S0 high
	//set S1 high
}

void red_read(void) // function to select red filter and display the count generated by the sensor on LCD. The count will be more if the color is red. The count will be very less if its blue or green.
{
	//Red
	//select red filter
	//reset the count to 0
	//capture the pulses for 100 ms or 0.1 second
	//store the count in variable called red

}

void green_read(void) // function to select green filter and display the count generated by the sensor on LCD. The count will be more if the color is green. The count will be very less if its blue or red.
{
	//Green
	//select green filter
	//reset the count to 0
	//capture the pulses for 100 ms or 0.1 second
	//store the count in variable called green

}

void blue_read(void) // function to select blue filter and display the count generated by the sensor on LCD. The count will be more if the color is blue. The count will be very less if its red or green.
{
	//Blue
	filter_blue(); //select blue filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	blue = pulse;  //store the count in variable called blue
	
}

int main(void)
{
    init_devices();
	color_sensor_scaling();
	
	while(1)
    {
      red_read();
	  green_read();
	  blue_read();
    }
}
